### ISSUE TITLE
Use i18n translations (messages) from vuei18n config file

### ISSUE THREAD

**Issue by MickL** [vue-email/vue-email#164] opened 2024-03-06 19:26 UTC
Using Nuxt and `@nuxtjs/i18n` I already have a translation config in `i18n.config.ts`:

```
export default defineI18nConfig(() => ({
  locale: 'en',
  messages: {
    en: {
      welcome: 'Welcome'
    },
    fr: {
      welcome: 'Bienvenue'
    }
  }
}))
```

This file is picked up automatically by Nuxt i18n. Would it be possible to use this file with its messages for the emails as well? Right now I declare the translations within `i18n.config.ts` and for emails within `nuxt.config.ts`.

Also I realized current translations can not be nested. For example I can create an object per email:

```
vueEmail: {
    baseUrl: getUrl(),
    autoImport: true,
    i18n: {
      defaultLocale: 'de',
      translations: {
        de: {
          invite: {
             greeting: 'hello',
          },
          accountCreated: {
             text: '...',
          }
        },
      },
    },
  },
```

Also Ive set the defaultLocale in `nuxt.config.ts` already for Nuxt i18n, can this also be reused maybe?

**Comment by Flowko** [comment] 2024-03-06 19:48
duplicate of https://github.com/vue-email/nuxt/issues/36

**Closed by Flowko** 2024-03-06 19:48 UTC
